name: mastodon
favicon: null
layout_spectrum: 0.14154469361528754
typography_spectrum: 0.5055272926110774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.47370627778582275
  lightness: 0.9486367215868086
  saturation: 0.33216547453776
  rhythmicContrast: 0.702129281591624
purpose: []
